server:
  port: 8082
  address: 0.0.0.0
spring:
  elasticsearch:
    uris: "elasticsearch:9200"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: trip-app